/**
 * Catalog data, generated from the gbdev Homebrew Hub database and filtered to
 * entries whose license was confirmed against the upstream repository AND whose
 * ROM was verified to boot and render under binjgb.
 *
 * See D-008. Do not add an entry without doing both checks.
 *
 * The shape is the shared manifest, not a ROM record: `runtime` picks the
 * host and `entry` is a ROM path only because these titles are emulated. A
 * native game sits in this same list with `runtime: "native"`.
 *
 * Ordered by curated rank, not alphabetically. Alphabetical put three
 * near-identical mazes in the first four tiles.
 *
 * The license filter decided what we *may* ship; it never decided what is worth
 * playing. Seven entries were cut for being duplicates of a better version or
 * for having nothing to distinguish them, and the descriptions and years were
 * written by hand from upstream sources — Homebrew Hub does not carry them. See
 * CATALOG_LINEUP.md for the per-title reasoning.
 *
 * Ranks 0-9 are the featured lineup; 10 and up are the rest of the library.
 */

import type { Game } from './types';

export const GAMES: readonly Game[] = [
  {
    slug: "drift",
    title: "Drift",
    developer: "GameBoyStudio",
    description: "One star, one ship, one button that matters. Thrust and gravity are the only forces, so every core you collect is a problem you solved with momentum you already had.",
    year: 2026,
    runtime: "native",
    console: null,
    genre: ["Action", "Score Attack"],
    entry: "drift",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/originals/drift.png"],
    license: "LicenseRef-GameBoyStudio-Original",
    attribution: "GameBoyStudio",
    sourceUrl: "",
    homepageUrl: "",
    rank: 0,
    series: null,
    saves: true,
  },
  {
    slug: "ring-out",
    title: "Ring Out",
    developer: "GameBoyStudio",
    description: "Two players, one screen, one shrinking platform. Move, dash, and shove the other player off. Rounds last about fifteen seconds and the rematch costs one button.",
    year: 2026,
    runtime: "native",
    console: null,
    genre: ["Party", "Versus"],
    entry: "ring-out",
    players: { min: 2, max: 2 },
    inputs: { required: [], supported: ["gamepad", "keyboard"] },
    screenshots: ["/originals/ring-out.png"],
    license: "LicenseRef-GameBoyStudio-Original",
    attribution: "GameBoyStudio",
    sourceUrl: "",
    homepageUrl: "",
    rank: 1,
    series: null,
    saves: false,
  },
  {
    slug: "tobutobugirldeluxe",
    title: "Tobu Tobu Girl Deluxe",
    developer: "Tangram Games",
    description: "Your cat is drifting up into the sky and the only way after it is other people's heads. Bounce off enemies to climb, dash in any of eight directions, and flap to squeeze out a little more height — then dash back down into something to earn the energy for the next flap. A colour remaster of the 2017 original.",
    year: 2019,
    runtime: "gbc",
    console: "GBC",
    genre: ["Action", "Arcade"],
    entry: "/roms/tobutobugirldeluxe.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/tobutobugirldeluxe-0.png", "/screenshots/tobutobugirldeluxe-1.png", "/screenshots/tobutobugirldeluxe-2.png"],
    license: "MIT",
    attribution: "Tangram Games",
    sourceUrl: "https://github.com/SimonLarsen/tobutobugirl-dx",
    homepageUrl: "https://tangramgames.itch.io/tobu-tobu-girl-deluxe",
    rank: 2,
    series: null,
    saves: true,
  },
  {
    slug: "shock-lobster",
    title: "Shock Lobster",
    developer: "tbsp",
    description: "You are a lobster with magic and a bad attitude, and the run will end — the only question is how far down. Dodge what is coming, shock what you can reach, and spend the pearls you collect on skills, upgrades and items that make the next attempt reach further than the last.",
    year: 2021,
    runtime: "gb",
    console: "GB",
    genre: ["Action", "Score Attack"],
    entry: "/roms/shock-lobster.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/shock-lobster-0.png", "/screenshots/shock-lobster-1.png", "/screenshots/shock-lobster-2.png"],
    license: "Zlib",
    attribution: "tbsp",
    sourceUrl: "https://github.com/tbsp/shock-lobster",
    homepageUrl: "",
    rank: 3,
    series: null,
    saves: true,
  },
  {
    slug: "gbhack",
    title: "GBHack",
    developer: "statico",
    description: "NetHack, on a Game Boy Color, without apology. Fifteen procedurally generated floors stand between you and the Amulet of Yendor, and between you and the floors stand hunger, unidentified potions, shopkeepers, traps and permadeath. Runs on original hardware.",
    year: 2026,
    runtime: "gbc",
    console: "GBC",
    genre: ["RPG", "Roguelike"],
    entry: "/roms/gbhack.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/gbhack-0.png", "/screenshots/gbhack-1.png"],
    license: "MIT",
    attribution: "statico",
    sourceUrl: "https://github.com/statico/gbhack",
    homepageUrl: "",
    rank: 4,
    series: null,
    saves: true,
  },
  {
    slug: "crossconnect",
    title: "CrossConnect",
    developer: "quinnp",
    description: "Join every pair of matching nodes with a line, and fill the entire board doing it — the second rule is what turns an easy puzzle into a real one. Hold A to draw, press B to erase, and hold Select in the menu to skip through pages of levels.",
    year: 2022,
    runtime: "gbc",
    console: "GBC",
    genre: ["Puzzle"],
    entry: "/roms/crossconnect.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/crossconnect-0.png", "/screenshots/crossconnect-1.png", "/screenshots/crossconnect-2.png"],
    license: "MIT",
    attribution: "quinnp",
    sourceUrl: "https://github.com/QuinnPainter/CrossConnect",
    homepageUrl: "",
    rank: 5,
    series: null,
    saves: true,
  },
  {
    slug: "europa-rescue",
    title: "Europa rescue!",
    developer: "godai / Gniazdo Światów",
    description: "The satellite base Europa stopped answering and went dark, and you are the one being sent up. Restore the power, repair what is broken, and work through the cargo crates and the experiments bay — a space station adventure with point-and-click bones, written by science-fiction author Bartek Biedrzycki and loosely built on the real Salyut 7 rescue.",
    year: 2022,
    runtime: "gbc",
    console: "GBC",
    genre: ["Adventure", "Puzzle"],
    entry: "/roms/europa-rescue.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/europa-rescue-0.png", "/screenshots/europa-rescue-1.png"],
    license: "CC-BY-SA-4.0",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/europa",
    homepageUrl: "",
    rank: 6,
    series: null,
    saves: true,
  },
  {
    slug: "aevilia",
    title: "Aevilia",
    developer: "ISSOtm, Kai, Parzival, Charmy",
    description: "A Game Boy Color role-playing game written from scratch in assembly. Pick your character and take the adventure it opens with at its word — this is the classic overworld-and-dialogue shape, built by hand at the lowest level the hardware allows.",
    year: 2018,
    runtime: "gbc",
    console: "GBC",
    genre: ["RPG"],
    entry: "/roms/aevilia.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/aevilia-0.png"],
    license: "Apache-2.0",
    attribution: "ISSOtm, Kai, Parzival, Charmy",
    sourceUrl: "https://github.com/ISSOtm/Aevilia-GB",
    homepageUrl: "",
    rank: 7,
    series: null,
    saves: true,
  },
  {
    slug: "renegade-rush",
    title: "Renegade Rush",
    developer: "quinnp",
    description: "Head down an open road at three hundred kilometres an hour with traffic in the way and a gun on the bonnet. Weave, shoot, keep the hearts you have left, and bank the money for whatever you can afford next.",
    year: 2021,
    runtime: "gb",
    console: "GB",
    genre: ["Action", "Racing"],
    entry: "/roms/renegade-rush.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/renegade-rush-0.png", "/screenshots/renegade-rush-1.png", "/screenshots/renegade-rush-2.png"],
    license: "MIT",
    attribution: "quinnp",
    sourceUrl: "https://github.com/QuinnPainter/Renegade-Rush",
    homepageUrl: "",
    rank: 8,
    series: null,
    saves: true,
  },
  {
    slug: "maxpirateeb",
    title: "Max Pirate Extra Boom",
    developer: "Lemmy Hawkins",
    description: "Zombies on the deck, an anchor in your hands, and a cannon named Bessie for everything the anchor cannot reach. A short, loud top-down brawler — this is the author's own expanded re-release of the 2024 original.",
    year: 2025,
    runtime: "gb",
    console: "GB",
    genre: ["Action"],
    entry: "/roms/maxpirateeb.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/maxpirateeb-0.png", "/screenshots/maxpirateeb-1.png", "/screenshots/maxpirateeb-2.png"],
    license: "MIT",
    attribution: "Lemmy Hawkins",
    sourceUrl: "https://github.com/MWehrstedt/MaxPirateExtra",
    homepageUrl: "",
    rank: 9,
    series: null,
    saves: false,
  },
  {
    slug: "2048gb",
    title: "2048gb",
    developer: "Sanqui",
    description: "The sliding-tile game that ate 2014, ported to the Game Boy in assembly. Push the board in one of four directions, watch equal numbers merge, and try to get to 2048 before the grid fills up.",
    year: 2014,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/2048gb.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/2048gb-0.png", "/screenshots/2048gb-1.png"],
    license: "Zlib",
    attribution: "Sanqui",
    sourceUrl: "https://github.com/Sanqui/2048-gb",
    homepageUrl: "",
    rank: 10,
    series: null,
    saves: true,
  },
  {
    slug: "flooder",
    title: "Flooder",
    developer: "Oliver Balfour",
    description: "Start in one corner and pick a colour; everything touching your territory in that colour joins it. Take the whole board in under twenty-five moves. Easy to hold in your head, hard to do well.",
    year: 2022,
    runtime: "gbc",
    console: "GBC",
    genre: ["Puzzle"],
    entry: "/roms/flooder.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/flooder-0.png", "/screenshots/flooder-1.png", "/screenshots/flooder-2.png"],
    license: "MIT",
    attribution: "Oliver Balfour",
    sourceUrl: "https://github.com/Obalfour/Flooder",
    homepageUrl: "https://www.ferrantecrafts.com/listing/1173804126/flooder-game-cartridge-for-game-boy",
    rank: 11,
    series: null,
    saves: false,
  },
  {
    slug: "labirinth",
    title: "Labirinth",
    developer: "godai / Gniazdo Światów",
    description: "You wake up somewhere that is not home, with seven hearts and no explanation. Talk to the people you meet, do what they ask, and the way forward opens — a small GB Studio adventure by the author of Europa rescue!",
    year: 2021,
    runtime: "gbc",
    console: "GBC",
    genre: ["Adventure", "RPG"],
    entry: "/roms/labirinth.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/labirinth-0.png", "/screenshots/labirinth-1.png"],
    license: "CC-BY-SA-4.0",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/labirinth",
    homepageUrl: "",
    rank: 12,
    series: null,
    saves: true,
  },
  {
    slug: "postbot",
    title: "PostBot",
    developer: "Tobias Rojahn",
    description: "Give the delivery robot its instructions up front, then watch them run and find out what you got wrong. The instruction list is shorter than the route, so the answer is always to find the piece that repeats.",
    year: 2018,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/postbot.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/postbot-0.png", "/screenshots/postbot-1.png", "/screenshots/postbot-2.png"],
    license: "MIT",
    attribution: "Tobias Rojahn",
    sourceUrl: "https://github.com/MasterIV/PostBot",
    homepageUrl: "http://rojahn.org/games/postbot/",
    rank: 13,
    series: null,
    saves: false,
  },
  {
    slug: "jp",
    title: "JP",
    developer: "Graham Coulby (IonicLimb)",
    description: "Climb by jumping and keep climbing. A small, unhurried platformer written in C, and a clean example of what one person builds first when they pick up the Game Boy.",
    year: 2021,
    runtime: "gb",
    console: "GB",
    genre: ["Platform"],
    entry: "/roms/jp.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    // jp-1 is the developer's logo splash, not the game. Dropped.
    screenshots: ["/screenshots/jp-0.png", "/screenshots/jp-2.png"],
    license: "MIT",
    attribution: "Graham Coulby (IonicLimb)",
    sourceUrl: "https://github.com/gcoulby/JP",
    homepageUrl: "https://grahamcoulby.co.uk/projects/jp-a-homebrew-gameboy-developed-in-c",
    rank: 14,
    series: null,
    saves: false,
  },
];
