/**
 * Catalog data, generated from the gbdev Homebrew Hub database and filtered to
 * entries whose license was confirmed against the upstream repository AND whose
 * ROM was verified to boot and render under binjgb.
 *
 * See D-008. Do not add an entry without doing both checks.
 */

import type { Game } from './types';

export const GAMES: readonly Game[] = [
  {
    slug: "2048gb",
    title: "2048gb",
    developer: "Sanqui",
    description: "",
    year: null,
    console: "GB",
    genre: ["Puzzle"],
    romPath: "/roms/2048gb.gb",
    romBytes: 32768,
    screenshots: ["/screenshots/2048gb-0.png", "/screenshots/2048gb-1.png"],
    license: "Zlib",
    attribution: "Sanqui",
    sourceUrl: "https://github.com/Sanqui/2048-gb",
    homepageUrl: "",
  },
  {
    slug: "5-mazes",
    title: "5 mazes",
    developer: "godai / Gniazdo Światów",
    description: "Help Alice get through mazes, each one larger and more difficult!",
    year: null,
    console: "GB",
    genre: ["Puzzle"],
    romPath: "/roms/5-mazes.gb",
    romBytes: 262144,
    screenshots: ["/screenshots/5-mazes-0.png", "/screenshots/5-mazes-1.png"],
    license: "MIT",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/5-Mazes",
    homepageUrl: "",
  },
  {
    slug: "5-mazes-master-levels",
    title: "5 mazes: Master levels",
    developer: "godai / Gniazdo Światów",
    description: "Help Alice get the ultimate set of largest mazes!",
    year: null,
    console: "GB",
    genre: ["Puzzle"],
    romPath: "/roms/5-mazes-master-levels.gb",
    romBytes: 524288,
    screenshots: ["/screenshots/5-mazes-master-levels-0.png", "/screenshots/5-mazes-master-levels-1.png"],
    license: "MIT",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/5-mazes-Master-levels",
    homepageUrl: "",
  },
  {
    slug: "5-more-mazes",
    title: "5 more mazes",
    developer: "godai / Gniazdo Światów",
    description: "Help Alice get through mazes, each one larger and more difficult!",
    year: null,
    console: "GB",
    genre: ["Puzzle"],
    romPath: "/roms/5-more-mazes.gb",
    romBytes: 262144,
    screenshots: ["/screenshots/5-more-mazes-0.png", "/screenshots/5-more-mazes-1.png"],
    license: "MIT",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/5-more-mazes",
    homepageUrl: "",
  },
  {
    slug: "aevilia",
    title: "Aevilia",
    developer: "ISSOtm, Kai, Parzival, Charmy",
    description: "",
    year: null,
    console: "GBC",
    genre: ["RPG"],
    romPath: "/roms/aevilia.gbc",
    romBytes: 131072,
    screenshots: ["/screenshots/aevilia-0.png"],
    license: "Apache-2.0",
    attribution: "ISSOtm, Kai, Parzival, Charmy",
    sourceUrl: "https://github.com/ISSOtm/Aevilia-GB",
    homepageUrl: "",
  },
  {
    slug: "crossconnect",
    title: "CrossConnect",
    developer: "quinnp",
    description: "",
    year: 2022,
    console: "GBC",
    genre: ["Puzzle"],
    romPath: "/roms/crossconnect.gbc",
    romBytes: 32768,
    screenshots: ["/screenshots/crossconnect-0.png", "/screenshots/crossconnect-1.png", "/screenshots/crossconnect-2.png"],
    license: "MIT",
    attribution: "quinnp",
    sourceUrl: "https://github.com/QuinnPainter/CrossConnect",
    homepageUrl: "",
  },
  {
    slug: "europa-rescue",
    title: "Europa rescue!",
    developer: "godai / Gniazdo Światów",
    description: "Repair a defunct space station. Single-handedly.",
    year: null,
    console: "GBC",
    genre: ["Adventure", "Puzzle"],
    romPath: "/roms/europa-rescue.gbc",
    romBytes: 1048576,
    screenshots: ["/screenshots/europa-rescue-0.png", "/screenshots/europa-rescue-1.png"],
    license: "CC-BY-SA-4.0",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/europa",
    homepageUrl: "",
  },
  {
    slug: "flooder",
    title: "Flooder",
    developer: "Oliver Balfour",
    description: "Can you flood the entire screen with a single color in less than 25 moves? Test your wits with this fun puzzle game.",
    year: null,
    console: "GBC",
    genre: ["Puzzle"],
    romPath: "/roms/flooder.gb",
    romBytes: 32768,
    screenshots: ["/screenshots/flooder-0.png", "/screenshots/flooder-1.png", "/screenshots/flooder-2.png"],
    license: "MIT",
    attribution: "Oliver Balfour",
    sourceUrl: "https://github.com/Obalfour/Flooder",
    homepageUrl: "https://www.ferrantecrafts.com/listing/1173804126/flooder-game-cartridge-for-game-boy",
  },
  {
    slug: "gbhack",
    title: "GBHack",
    developer: "statico",
    description: "A roguelike dungeon crawler for the Game Boy Color inspired by NetHack. Descend 15 procedurally generated dungeon levels through permadeath, unidentified items, hunger, pets, shops, and traps to retrieve the Amulet of Yendor. Runs on original GBC hardware. Written in C with GBDK and generated with Claude Code.",
    year: 2026,
    console: "GBC",
    genre: ["RPG"],
    romPath: "/roms/gbhack.gbc",
    romBytes: 262144,
    screenshots: ["/screenshots/gbhack-0.png", "/screenshots/gbhack-1.png"],
    license: "MIT",
    attribution: "statico",
    sourceUrl: "https://github.com/statico/gbhack",
    homepageUrl: "",
  },
  {
    slug: "jp",
    title: "JP",
    developer: "Graham Coulby (IonicLimb)",
    description: "A casual jumping platform game",
    year: 2021,
    console: "GB",
    genre: ["Platform"],
    romPath: "/roms/jp.gb",
    romBytes: 65536,
    screenshots: ["/screenshots/jp-0.png", "/screenshots/jp-1.png", "/screenshots/jp-2.png"],
    license: "MIT",
    attribution: "Graham Coulby (IonicLimb)",
    sourceUrl: "https://github.com/gcoulby/JP",
    homepageUrl: "https://grahamcoulby.co.uk/projects/jp-a-homebrew-gameboy-developed-in-c",
  },
  {
    slug: "labirinth",
    title: "Labirinth",
    developer: "godai / Gniazdo Światów",
    description: "Lost in a strange world, proceed by helping the poeple you meet on your way",
    year: null,
    console: "GBC",
    genre: ["Adventure", "RPG"],
    romPath: "/roms/labirinth.gbc",
    romBytes: 524288,
    screenshots: ["/screenshots/labirinth-0.png", "/screenshots/labirinth-1.png"],
    license: "CC-BY-SA-4.0",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/labirinth",
    homepageUrl: "",
  },
  {
    slug: "maxpirate",
    title: "Max Pirate",
    developer: "Lemmy Hawkins",
    description: "A small action game. Smash zombies with your anchor and your cannon Bessie. Made with GBDK-2020.",
    year: 2024,
    console: "GB",
    genre: ["Action"],
    romPath: "/roms/maxpirate.gb",
    romBytes: 32768,
    screenshots: ["/screenshots/maxpirate-0.png", "/screenshots/maxpirate-1.png", "/screenshots/maxpirate-2.png"],
    license: "MIT",
    attribution: "Lemmy Hawkins",
    sourceUrl: "https://github.com/MWehrstedt/MaxPirate",
    homepageUrl: "",
  },
  {
    slug: "maxpirateeb",
    title: "Max Pirate Extra Boom",
    developer: "Lemmy Hawkins",
    description: "Updated re-release for the original game. Smash zombies with your anchor and your cannon Bessie. Made with GBDK-2020.",
    year: 2025,
    console: "GB",
    genre: ["Action"],
    romPath: "/roms/maxpirateeb.gb",
    romBytes: 65536,
    screenshots: ["/screenshots/maxpirateeb-0.png", "/screenshots/maxpirateeb-1.png", "/screenshots/maxpirateeb-2.png"],
    license: "MIT",
    attribution: "Lemmy Hawkins",
    sourceUrl: "https://github.com/MWehrstedt/MaxPirateExtra",
    homepageUrl: "",
  },
  {
    slug: "postbot",
    title: "PostBot",
    developer: "Tobias Rojahn",
    description: "",
    year: null,
    console: "GB",
    genre: ["Puzzle"],
    romPath: "/roms/postbot.gb",
    romBytes: 65536,
    screenshots: ["/screenshots/postbot-0.png", "/screenshots/postbot-1.png", "/screenshots/postbot-2.png"],
    license: "MIT",
    attribution: "Tobias Rojahn",
    sourceUrl: "https://github.com/MasterIV/PostBot",
    homepageUrl: "",
  },
  {
    slug: "renegade-rush",
    title: "Renegade Rush",
    developer: "quinnp",
    description: "",
    year: 2021,
    console: "GB",
    genre: ["gbcompo21", "gbcompo21-shortlist"],
    romPath: "/roms/renegade-rush.gb",
    romBytes: 65536,
    screenshots: ["/screenshots/renegade-rush-0.png", "/screenshots/renegade-rush-1.png", "/screenshots/renegade-rush-2.png"],
    license: "MIT",
    attribution: "quinnp",
    sourceUrl: "https://github.com/QuinnPainter/Renegade-Rush",
    homepageUrl: "",
  },
  {
    slug: "shock-lobster",
    title: "Shock Lobster",
    developer: "tbsp",
    description: "",
    year: null,
    console: "GB",
    genre: ["gbcompo21", "gbcompo21-shortlist"],
    romPath: "/roms/shock-lobster.gb",
    romBytes: 32768,
    screenshots: ["/screenshots/shock-lobster-0.png", "/screenshots/shock-lobster-1.png", "/screenshots/shock-lobster-2.png"],
    license: "Zlib",
    attribution: "tbsp",
    sourceUrl: "https://github.com/tbsp/shock-lobster",
    homepageUrl: "",
  },
  {
    slug: "snake",
    title: "Snake",
    developer: "Yvar de Goffau",
    description: "",
    year: null,
    console: "GBC",
    genre: [],
    romPath: "/roms/snake.gb",
    romBytes: 32768,
    screenshots: ["/screenshots/snake-0.png"],
    license: "WTFPL-2.0",
    attribution: "Yvar de Goffau",
    sourceUrl: "https://github.com/Yvar-deGoffau/GBSnake",
    homepageUrl: "http://forums.nesdev.com/viewtopic.php?f=20&t=16787&sid=86fe28e1d07a7d0a7cf9775104d6a4a9",
  },
  {
    slug: "squishy-the-turtle",
    title: "Squishy the Turtle",
    developer: "Cppchriscpp",
    description: "",
    year: 2015,
    console: "GB",
    genre: [],
    romPath: "/roms/squishy-the-turtle.gb",
    romBytes: 131072,
    screenshots: ["/screenshots/squishy-the-turtle-0.png"],
    license: "MIT",
    attribution: "Cppchriscpp",
    sourceUrl: "https://github.com/potatolain/SquishyTheTurtle",
    homepageUrl: "",
  },
  {
    slug: "tobutobugirl",
    title: "Tobu Tobu Girl",
    developer: "Tangram Games",
    description: "",
    year: 2017,
    console: "GB",
    genre: ["Action"],
    romPath: "/roms/tobutobugirl.gb",
    romBytes: 262144,
    screenshots: ["/screenshots/tobutobugirl-0.png"],
    license: "MIT",
    attribution: "Tangram Games",
    sourceUrl: "https://github.com/SimonLarsen/tobutobugirl",
    homepageUrl: "https://tangramgames.itch.io/tobutobugirl",
  },
  {
    slug: "tobutobugirldeluxe",
    title: "Tobu Tobu Girl Deluxe",
    developer: "Tangram Games",
    description: "",
    year: null,
    console: "GBC",
    genre: ["Action"],
    romPath: "/roms/tobutobugirldeluxe.gb",
    romBytes: 262144,
    screenshots: ["/screenshots/tobutobugirldeluxe-0.png", "/screenshots/tobutobugirldeluxe-1.png", "/screenshots/tobutobugirldeluxe-2.png"],
    license: "MIT",
    attribution: "Tangram Games",
    sourceUrl: "https://github.com/SimonLarsen/tobutobugirl-dx",
    homepageUrl: "https://tangramgames.itch.io/tobu-tobu-girl-deluxe",
  },
];
