/**
 * Catalog data, generated from the gbdev Homebrew Hub database and filtered to
 * entries whose license was confirmed against the upstream repository AND whose
 * ROM was verified to boot and render under binjgb.
 *
 * See D-008. Do not add an entry without doing both checks.
 *
 * The shape is the shared manifest, not a ROM record: `runtime` picks the
 * host and `entry` is a ROM path only because these titles are emulated. A
 * native game sits in this same list with `runtime: "native"`.
 *
 * Ordered by curated rank, not alphabetically. Alphabetical put three
 * near-identical mazes in the first four tiles.
 */

import type { Game } from './types';

export const GAMES: readonly Game[] = [
  {
    slug: "drift",
    title: "Drift",
    developer: "GameBoyStudio",
    description: "One star, one ship, one button that matters. Thrust and gravity are the only forces, so every core you collect is a problem you solved with momentum you already had.",
    year: 2026,
    runtime: "native",
    console: null,
    genre: ["Action", "Score Attack"],
    entry: "drift",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/originals/drift.png"],
    license: "LicenseRef-GameBoyStudio-Original",
    attribution: "GameBoyStudio",
    sourceUrl: "",
    homepageUrl: "",
    rank: 0,
    series: null,
    saves: true,
  },
  {
    slug: "ring-out",
    title: "Ring Out",
    developer: "GameBoyStudio",
    description: "Two players, one screen, one shrinking platform. Move, dash, and shove the other player off. Rounds last about fifteen seconds and the rematch costs one button.",
    year: 2026,
    runtime: "native",
    console: null,
    genre: ["Party", "Versus"],
    entry: "ring-out",
    players: { min: 2, max: 2 },
    inputs: { required: [], supported: ["gamepad", "keyboard"] },
    screenshots: ["/originals/ring-out.png"],
    license: "LicenseRef-GameBoyStudio-Original",
    attribution: "GameBoyStudio",
    sourceUrl: "",
    homepageUrl: "",
    rank: 1,
    series: null,
    saves: false,
  },
  {
    slug: "tobutobugirldeluxe",
    title: "Tobu Tobu Girl Deluxe",
    developer: "Tangram Games",
    description: "",
    year: null,
    runtime: "gbc",
    console: "GBC",
    genre: ["Action"],
    entry: "/roms/tobutobugirldeluxe.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/tobutobugirldeluxe-0.png", "/screenshots/tobutobugirldeluxe-1.png", "/screenshots/tobutobugirldeluxe-2.png"],
    license: "MIT",
    attribution: "Tangram Games",
    sourceUrl: "https://github.com/SimonLarsen/tobutobugirl-dx",
    homepageUrl: "https://tangramgames.itch.io/tobu-tobu-girl-deluxe",
    rank: 2,
    series: "Tobu Tobu Girl",
    saves: true,
  },
  {
    slug: "aevilia",
    title: "Aevilia",
    developer: "ISSOtm, Kai, Parzival, Charmy",
    description: "",
    year: null,
    runtime: "gbc",
    console: "GBC",
    genre: ["RPG"],
    entry: "/roms/aevilia.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/aevilia-0.png"],
    license: "Apache-2.0",
    attribution: "ISSOtm, Kai, Parzival, Charmy",
    sourceUrl: "https://github.com/ISSOtm/Aevilia-GB",
    homepageUrl: "",
    rank: 3,
    series: null,
    saves: true,
  },
  {
    slug: "2048gb",
    title: "2048gb",
    developer: "Sanqui",
    description: "",
    year: null,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/2048gb.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/2048gb-0.png", "/screenshots/2048gb-1.png"],
    license: "Zlib",
    attribution: "Sanqui",
    sourceUrl: "https://github.com/Sanqui/2048-gb",
    homepageUrl: "",
    rank: 4,
    series: null,
    saves: true,
  },
  {
    slug: "gbhack",
    title: "GBHack",
    developer: "statico",
    description: "A roguelike dungeon crawler for the Game Boy Color inspired by NetHack. Descend 15 procedurally generated dungeon levels through permadeath, unidentified items, hunger, pets, shops, and traps to retrieve the Amulet of Yendor. Runs on original GBC hardware. Written in C with GBDK and generated with Claude Code.",
    year: 2026,
    runtime: "gbc",
    console: "GBC",
    genre: ["RPG"],
    entry: "/roms/gbhack.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/gbhack-0.png", "/screenshots/gbhack-1.png"],
    license: "MIT",
    attribution: "statico",
    sourceUrl: "https://github.com/statico/gbhack",
    homepageUrl: "",
    rank: 5,
    series: null,
    saves: true,
  },
  {
    slug: "snake",
    title: "Snake",
    developer: "Yvar de Goffau",
    description: "",
    year: null,
    runtime: "gbc",
    console: "GBC",
    genre: [],
    entry: "/roms/snake.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/snake-0.png"],
    license: "WTFPL-2.0",
    attribution: "Yvar de Goffau",
    sourceUrl: "https://github.com/Yvar-deGoffau/GBSnake",
    homepageUrl: "http://forums.nesdev.com/viewtopic.php?f=20&t=16787&sid=86fe28e1d07a7d0a7cf9775104d6a4a9",
    rank: 6,
    series: null,
    saves: false,
  },
  {
    slug: "crossconnect",
    title: "CrossConnect",
    developer: "quinnp",
    description: "",
    year: 2022,
    runtime: "gbc",
    console: "GBC",
    genre: ["Puzzle"],
    entry: "/roms/crossconnect.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/crossconnect-0.png", "/screenshots/crossconnect-1.png", "/screenshots/crossconnect-2.png"],
    license: "MIT",
    attribution: "quinnp",
    sourceUrl: "https://github.com/QuinnPainter/CrossConnect",
    homepageUrl: "",
    rank: 7,
    series: null,
    saves: true,
  },
  {
    slug: "shock-lobster",
    title: "Shock Lobster",
    developer: "tbsp",
    description: "",
    year: null,
    runtime: "gb",
    console: "GB",
    genre: ["gbcompo21", "gbcompo21-shortlist"],
    entry: "/roms/shock-lobster.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/shock-lobster-0.png", "/screenshots/shock-lobster-1.png", "/screenshots/shock-lobster-2.png"],
    license: "Zlib",
    attribution: "tbsp",
    sourceUrl: "https://github.com/tbsp/shock-lobster",
    homepageUrl: "",
    rank: 8,
    series: null,
    saves: true,
  },
  {
    slug: "flooder",
    title: "Flooder",
    developer: "Oliver Balfour",
    description: "Can you flood the entire screen with a single color in less than 25 moves? Test your wits with this fun puzzle game.",
    year: null,
    runtime: "gbc",
    console: "GBC",
    genre: ["Puzzle"],
    entry: "/roms/flooder.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/flooder-0.png", "/screenshots/flooder-1.png", "/screenshots/flooder-2.png"],
    license: "MIT",
    attribution: "Oliver Balfour",
    sourceUrl: "https://github.com/Obalfour/Flooder",
    homepageUrl: "https://www.ferrantecrafts.com/listing/1173804126/flooder-game-cartridge-for-game-boy",
    rank: 9,
    series: null,
    saves: false,
  },
  {
    slug: "squishy-the-turtle",
    title: "Squishy the Turtle",
    developer: "Cppchriscpp",
    description: "",
    year: 2015,
    runtime: "gb",
    console: "GB",
    genre: [],
    entry: "/roms/squishy-the-turtle.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/squishy-the-turtle-0.png"],
    license: "MIT",
    attribution: "Cppchriscpp",
    sourceUrl: "https://github.com/potatolain/SquishyTheTurtle",
    homepageUrl: "",
    rank: 10,
    series: null,
    saves: true,
  },
  {
    slug: "europa-rescue",
    title: "Europa rescue!",
    developer: "godai / Gniazdo Światów",
    description: "Repair a defunct space station. Single-handedly.",
    year: null,
    runtime: "gbc",
    console: "GBC",
    genre: ["Adventure", "Puzzle"],
    entry: "/roms/europa-rescue.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/europa-rescue-0.png", "/screenshots/europa-rescue-1.png"],
    license: "CC-BY-SA-4.0",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/europa",
    homepageUrl: "",
    rank: 11,
    series: null,
    saves: true,
  },
  {
    slug: "renegade-rush",
    title: "Renegade Rush",
    developer: "quinnp",
    description: "",
    year: 2021,
    runtime: "gb",
    console: "GB",
    genre: ["gbcompo21", "gbcompo21-shortlist"],
    entry: "/roms/renegade-rush.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/renegade-rush-0.png", "/screenshots/renegade-rush-1.png", "/screenshots/renegade-rush-2.png"],
    license: "MIT",
    attribution: "quinnp",
    sourceUrl: "https://github.com/QuinnPainter/Renegade-Rush",
    homepageUrl: "",
    rank: 12,
    series: null,
    saves: true,
  },
  {
    slug: "postbot",
    title: "PostBot",
    developer: "Tobias Rojahn",
    description: "",
    year: null,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/postbot.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/postbot-0.png", "/screenshots/postbot-1.png", "/screenshots/postbot-2.png"],
    license: "MIT",
    attribution: "Tobias Rojahn",
    sourceUrl: "https://github.com/MasterIV/PostBot",
    homepageUrl: "",
    rank: 13,
    series: null,
    saves: false,
  },
  {
    slug: "maxpirate",
    title: "Max Pirate",
    developer: "Lemmy Hawkins",
    description: "A small action game. Smash zombies with your anchor and your cannon Bessie. Made with GBDK-2020.",
    year: 2024,
    runtime: "gb",
    console: "GB",
    genre: ["Action"],
    entry: "/roms/maxpirate.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/maxpirate-0.png", "/screenshots/maxpirate-1.png", "/screenshots/maxpirate-2.png"],
    license: "MIT",
    attribution: "Lemmy Hawkins",
    sourceUrl: "https://github.com/MWehrstedt/MaxPirate",
    homepageUrl: "",
    rank: 14,
    series: "Max Pirate",
    saves: false,
  },
  {
    slug: "tobutobugirl",
    title: "Tobu Tobu Girl",
    developer: "Tangram Games",
    description: "",
    year: 2017,
    runtime: "gb",
    console: "GB",
    genre: ["Action"],
    entry: "/roms/tobutobugirl.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/tobutobugirl-0.png"],
    license: "MIT",
    attribution: "Tangram Games",
    sourceUrl: "https://github.com/SimonLarsen/tobutobugirl",
    homepageUrl: "https://tangramgames.itch.io/tobutobugirl",
    rank: 15,
    series: "Tobu Tobu Girl",
    saves: true,
  },
  {
    slug: "labirinth",
    title: "Labirinth",
    developer: "godai / Gniazdo Światów",
    description: "Lost in a strange world, proceed by helping the poeple you meet on your way",
    year: null,
    runtime: "gbc",
    console: "GBC",
    genre: ["Adventure", "RPG"],
    entry: "/roms/labirinth.gbc",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/labirinth-0.png", "/screenshots/labirinth-1.png"],
    license: "CC-BY-SA-4.0",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/labirinth",
    homepageUrl: "",
    rank: 16,
    series: null,
    saves: true,
  },
  {
    slug: "jp",
    title: "JP",
    developer: "Graham Coulby (IonicLimb)",
    description: "A casual jumping platform game",
    year: 2021,
    runtime: "gb",
    console: "GB",
    genre: ["Platform"],
    entry: "/roms/jp.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/jp-0.png", "/screenshots/jp-1.png", "/screenshots/jp-2.png"],
    license: "MIT",
    attribution: "Graham Coulby (IonicLimb)",
    sourceUrl: "https://github.com/gcoulby/JP",
    homepageUrl: "https://grahamcoulby.co.uk/projects/jp-a-homebrew-gameboy-developed-in-c",
    rank: 17,
    series: null,
    saves: false,
  },
  {
    slug: "5-mazes",
    title: "5 mazes",
    developer: "godai / Gniazdo Światów",
    description: "Help Alice get through mazes, each one larger and more difficult!",
    year: null,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/5-mazes.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/5-mazes-0.png", "/screenshots/5-mazes-1.png"],
    license: "MIT",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/5-Mazes",
    homepageUrl: "",
    rank: 18,
    series: "5 mazes",
    saves: true,
  },
  {
    slug: "maxpirateeb",
    title: "Max Pirate Extra Boom",
    developer: "Lemmy Hawkins",
    description: "Updated re-release for the original game. Smash zombies with your anchor and your cannon Bessie. Made with GBDK-2020.",
    year: 2025,
    runtime: "gb",
    console: "GB",
    genre: ["Action"],
    entry: "/roms/maxpirateeb.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/maxpirateeb-0.png", "/screenshots/maxpirateeb-1.png", "/screenshots/maxpirateeb-2.png"],
    license: "MIT",
    attribution: "Lemmy Hawkins",
    sourceUrl: "https://github.com/MWehrstedt/MaxPirateExtra",
    homepageUrl: "",
    rank: 19,
    series: "Max Pirate",
    saves: false,
  },
  {
    slug: "5-more-mazes",
    title: "5 more mazes",
    developer: "godai / Gniazdo Światów",
    description: "Help Alice get through mazes, each one larger and more difficult!",
    year: null,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/5-more-mazes.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/5-more-mazes-0.png", "/screenshots/5-more-mazes-1.png"],
    license: "MIT",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/5-more-mazes",
    homepageUrl: "",
    rank: 20,
    series: "5 mazes",
    saves: true,
  },
  {
    slug: "5-mazes-master-levels",
    title: "5 mazes: Master levels",
    developer: "godai / Gniazdo Światów",
    description: "Help Alice get the ultimate set of largest mazes!",
    year: null,
    runtime: "gb",
    console: "GB",
    genre: ["Puzzle"],
    entry: "/roms/5-mazes-master-levels.gb",
    players: { min: 1, max: 1 },
    inputs: { required: [], supported: ["gamepad", "keyboard", "touch"] },
    screenshots: ["/screenshots/5-mazes-master-levels-0.png", "/screenshots/5-mazes-master-levels-1.png"],
    license: "MIT",
    attribution: "godai / Gniazdo Światów",
    sourceUrl: "https://github.com/godai78/5-mazes-Master-levels",
    homepageUrl: "",
    rank: 21,
    series: "5 mazes",
    saves: true,
  },
];
