/**
 * Composing a game from a spec, using the toolbox.
 *
 * This is the no-model generator (D-025). It is deliberately not a lookup of
 * canned files: it assembles source from the spec's knobs, so the pipeline is
 * genuinely exercised and swapping in a model changes only which function
 * produces the source.
 *
 * It is also research. A rule-based composer over the toolbox is a proto-schema
 * — what it can express is a first draft of what a declarative format would
 * need to contain, and every request it cannot express is a gap in that draft.
 * The parts it finds awkward are recorded rather than smoothed over.
 *
 * Every game it emits uses toolbox primitives rather than reinventing them,
 * which is the property the corpus run measures.
 */

import type { GameSpec } from './project.js';
import type { Kind } from './spec.js';

const num = (spec: GameSpec, key: string, fallback: number): number => {
  const value = spec.tuning[key];
  return typeof value === 'number' ? value : fallback;
};

/** Shared by every emitted game: the imports and the wiring the SDK expects. */
function preamble(spec: GameSpec): string {
  return `/**
 * ${spec.title} — generated by GameBoyStudio.
 *
 * Composed from a request, not written by hand. It uses the toolbox rather
 * than reimplementing phases, drawing, saves or randomness, which is the whole
 * point of there being a toolbox.
 */
import { runHostedGame, type HostedGameContext, type HostedInput } from '@gameboystudio/sdk';
import {
  Phases,
  Random,
  RESOLUTION,
  bestScore,
  centered,
  circle,
  clear,
  panel,
  rect,
  text,
} from '@gameboystudio/sdk/toolbox';

const W = RESOLUTION.width;
const H = RESOLUTION.height;
const codec = bestScore(9999);
const rng = new Random();
`;
}

function footer(): string {
  return `
const game = new Game();
runHostedGame({
  width: W,
  height: H,
  init: (context) => game.init(context),
  update: (dt, input) => game.update(dt, input),
  render: (g) => game.render(g),
  serialize: () => game.serialize(),
  restore: (data) => game.restore(data),
});
`;
}

/** Save methods, emitted the same way for every kind because the toolbox owns it. */
function saveMethods(spec: GameSpec): string {
  if (!spec.saves) {
    return `
  serialize(): Uint8Array { return new Uint8Array(0); }
  restore(): void {}
`;
  }
  return `
  serialize(): Uint8Array {
    return codec.serialize(this.best);
  }

  restore(data: Uint8Array): void {
    const stored = codec.restore(data);
    if (stored !== null) this.best = stored;
  }
`;
}

function collect(spec: GameSpec): string {
  const speed = num(spec, 'speed', 110);
  const targets = num(spec, 'targets', 3);
  const seconds = num(spec, 'seconds', 45);
  const players = spec.players.max;

  return `${preamble(spec)}
type P = 'ready' | 'play' | 'over';

interface Dot { x: number; y: number; taken: boolean }
interface Mover { x: number; y: number; score: number }

class Game {
  private phases = new Phases<P>('ready');
  private movers: Mover[] = [];
  private dots: Dot[] = [];
  private best = 0;
  private ctx: HostedGameContext | null = null;

  init(context: HostedGameContext): void {
    this.ctx = context;
    this.phases.reset('ready');
    this.movers = Array.from({ length: ${players} }, (_, i) => ({
      x: W / 2 + (i === 0 ? -40 : 40), y: H / 2, score: 0,
    }));
    this.scatter();
  }

  private scatter(): void {
    this.dots = Array.from({ length: ${targets} }, () => ({
      x: rng.float(24, W - 24), y: rng.float(48, H - 32), taken: false,
    }));
  }

  update(dt: number, input: HostedInput): void {
    this.phases.advance(dt);

    if (this.phases.is('ready')) {
      if (input.pressed(0, 'a') || input.pressed(0, 'start')) this.phases.to('play');
      return;
    }
    if (this.phases.is('over')) {
      if (input.pressed(0, 'a') || input.pressed(0, 'start')) this.init(this.ctx!);
      return;
    }

    for (let p = 0; p < this.movers.length; p += 1) {
      const mover = this.movers[p];
      const step = ${speed} * dt;
      if (input.held(p, 'left')) mover.x -= step;
      if (input.held(p, 'right')) mover.x += step;
      if (input.held(p, 'up')) mover.y -= step;
      if (input.held(p, 'down')) mover.y += step;
      mover.x = Math.max(8, Math.min(W - 8, mover.x));
      mover.y = Math.max(8, Math.min(H - 8, mover.y));

      for (const dot of this.dots) {
        if (dot.taken) continue;
        if (Math.hypot(dot.x - mover.x, dot.y - mover.y) < 14) {
          dot.taken = true;
          mover.score += 1;
          if (mover.score > this.best) { this.best = mover.score; this.ctx?.saveDirty(); }
        }
      }
    }

    if (this.dots.every((dot) => dot.taken)) this.scatter();
    ${seconds > 0 ? `if (this.phases.phaseFor > ${seconds}) this.phases.to('over');` : ''}
  }

  render(g: CanvasRenderingContext2D): void {
    clear(g);
    for (const dot of this.dots) {
      if (!dot.taken) circle(g, dot.x, dot.y, 6, 'amber');
    }
    this.movers.forEach((mover, i) => circle(g, mover.x, mover.y, 9, i === 0 ? 'lcd' : 'amber'));

    centered(g, 'SCORE ' + this.movers.map((m) => m.score).join(' - '), 22, { size: 11, fill: 'muted' });
    centered(g, 'BEST ' + String(this.best).padStart(2, '0'), 38, { size: 11, fill: 'faint' });
    ${seconds > 0 ? `if (this.phases.is('play')) centered(g, String(Math.max(0, Math.ceil(${seconds} - this.phases.phaseFor))), 54, { size: 11, fill: 'faint' });` : ''}
    if (this.phases.is('ready')) centered(g, 'PRESS A TO START', H - 26, { size: 13 });
    if (this.phases.is('over')) centered(g, 'TIME — PRESS A', H - 26, { size: 13 });
  }
${saveMethods(spec)}}
${footer()}`;
}

function dodge(spec: GameSpec): string {
  const speed = num(spec, 'speed', 130);
  const hazards = num(spec, 'hazards', 4);
  const lives = num(spec, 'lives', 3);

  return `${preamble(spec)}
type P = 'ready' | 'play' | 'hit' | 'over';

interface Hazard { x: number; y: number; vy: number }

class Game {
  private phases = new Phases<P>('ready');
  private x = W / 2;
  private hazards: Hazard[] = [];
  private lives = ${lives};
  private survived = 0;
  private best = 0;
  private ctx: HostedGameContext | null = null;

  init(context: HostedGameContext): void {
    this.ctx = context;
    this.phases.reset('ready');
    this.x = W / 2;
    this.lives = ${lives};
    this.survived = 0;
    this.hazards = Array.from({ length: ${hazards} }, () => this.spawn());
  }

  private spawn(): Hazard {
    return { x: rng.float(16, W - 16), y: rng.float(-H, 0), vy: rng.float(60, ${speed}) };
  }

  update(dt: number, input: HostedInput): void {
    this.phases.advance(dt);

    if (this.phases.is('ready', 'over')) {
      if (input.pressed(0, 'a') || input.pressed(0, 'start')) {
        if (this.phases.is('over')) this.init(this.ctx!);
        this.phases.to('play');
      }
      return;
    }
    if (this.phases.is('hit')) {
      if (this.phases.after(0.9, 'play')) this.hazards = this.hazards.map(() => this.spawn());
      return;
    }

    const step = ${speed} * dt;
    if (input.held(0, 'left')) this.x -= step;
    if (input.held(0, 'right')) this.x += step;
    this.x = Math.max(10, Math.min(W - 10, this.x));

    this.survived += dt;
    if (Math.floor(this.survived) > this.best) {
      this.best = Math.floor(this.survived);
      this.ctx?.saveDirty();
    }

    for (const hazard of this.hazards) {
      hazard.y += hazard.vy * dt;
      if (hazard.y > H + 10) Object.assign(hazard, this.spawn());
      if (Math.abs(hazard.x - this.x) < 14 && Math.abs(hazard.y - (H - 28)) < 14) {
        this.lives -= 1;
        this.phases.to(this.lives > 0 ? 'hit' : 'over');
        return;
      }
    }
  }

  render(g: CanvasRenderingContext2D): void {
    clear(g);
    for (const hazard of this.hazards) rect(g, hazard.x - 7, hazard.y - 7, 14, 14, 'danger');
    circle(g, this.x, H - 28, 10, this.phases.is('hit') ? 'danger' : 'lcd');

    centered(g, 'TIME ' + String(Math.floor(this.survived)).padStart(3, '0'), 22, { size: 11, fill: 'muted' });
    centered(g, 'BEST ' + String(this.best).padStart(3, '0'), 38, { size: 11, fill: 'faint' });
    text(g, 'LIVES ' + '*'.repeat(Math.max(0, this.lives)), 12, 22, { size: 11, fill: 'amber' });

    if (this.phases.is('ready')) centered(g, 'PRESS A TO START', H - 60, { size: 13 });
    if (this.phases.is('over')) centered(g, 'CAUGHT — PRESS A', H - 60, { size: 13, fill: 'danger' });
  }
${saveMethods(spec)}}
${footer()}`;
}

function memory(spec: GameSpec): string {
  const flash = num(spec, 'flashSeconds', 0.42);
  const gap = num(spec, 'gapSeconds', 0.16);

  return `${preamble(spec)}
type P = 'ready' | 'showing' | 'repeating' | 'wrong' | 'over';
type Button = 'up' | 'down' | 'left' | 'right';

const PANELS: { button: Button; dx: number; dy: number }[] = [
  { button: 'up', dx: 0, dy: -1 },
  { button: 'left', dx: -1, dy: 0 },
  { button: 'right', dx: 1, dy: 0 },
  { button: 'down', dx: 0, dy: 1 },
];

class Game {
  private phases = new Phases<P>('ready');
  private pattern: Button[] = [];
  private step = 0;
  private lit: Button | null = null;
  private best = 0;
  private ctx: HostedGameContext | null = null;

  init(context: HostedGameContext): void {
    this.ctx = context;
    this.phases.reset('ready');
    this.pattern = [];
    this.step = 0;
    this.lit = null;
  }

  private extend(): void {
    this.pattern.push(rng.pick(PANELS).button);
    this.step = 0;
    this.lit = null;
    this.phases.to('showing');
  }

  update(dt: number, input: HostedInput): void {
    this.phases.advance(dt);

    if (this.phases.is('ready', 'over')) {
      if (input.pressed(0, 'a') || input.pressed(0, 'start')) {
        this.pattern = [];
        this.extend();
      }
      return;
    }

    if (this.phases.is('showing')) {
      const slot = ${flash} + ${gap};
      const index = Math.floor(this.phases.phaseFor / slot);
      if (index >= this.pattern.length) {
        this.step = 0;
        this.lit = null;
        this.phases.to('repeating');
        return;
      }
      this.lit = this.phases.phaseFor - index * slot < ${flash} ? this.pattern[index] : null;
      return;
    }

    if (this.phases.is('wrong')) {
      this.phases.after(1.1, 'over');
      return;
    }

    for (const panelDef of PANELS) {
      if (!input.pressed(0, panelDef.button)) continue;
      if (panelDef.button === this.pattern[this.step]) {
        this.lit = panelDef.button;
        this.step += 1;
        if (this.step >= this.pattern.length) {
          if (this.pattern.length > this.best) {
            this.best = this.pattern.length;
            this.ctx?.saveDirty();
          }
          this.extend();
        }
      } else {
        this.lit = null;
        this.phases.to('wrong');
      }
      return;
    }
    if (this.phases.phaseFor > 0.2) this.lit = null;
  }

  render(g: CanvasRenderingContext2D): void {
    clear(g);
    const size = 64;
    const gapPx = 6;
    for (const panelDef of PANELS) {
      const x = W / 2 + panelDef.dx * (size + gapPx) - size / 2;
      const y = H / 2 + 8 + panelDef.dy * (size + gapPx) - size / 2;
      const on = this.lit === panelDef.button;
      panel(g, x, y, size, size, on ? 'lcd' : 'panel');
    }

    centered(g, 'ROUND ' + String(this.pattern.length).padStart(2, '0'), 24, { size: 11, fill: 'muted' });
    centered(g, 'BEST ' + String(this.best).padStart(2, '0'), 40, { size: 11, fill: 'faint' });

    if (this.phases.is('ready')) centered(g, 'PRESS A TO BEGIN', H - 26, { size: 13 });
    if (this.phases.is('showing')) centered(g, 'WATCH', H - 26, { size: 13 });
    if (this.phases.is('repeating')) centered(g, 'REPEAT IT', H - 26, { size: 13 });
    if (this.phases.is('wrong')) centered(g, 'WRONG', H - 26, { size: 13, fill: 'danger' });
    if (this.phases.is('over')) centered(g, 'PRESS A TO TRY AGAIN', H - 26, { size: 13 });
  }
${saveMethods(spec)}}
${footer()}`;
}

function reaction(spec: GameSpec): string {
  const rounds = num(spec, 'rounds', 5);
  const minWait = num(spec, 'minWait', 0.8);
  const maxWait = num(spec, 'maxWait', 2.6);

  return `${preamble(spec)}
type P = 'ready' | 'waiting' | 'now' | 'tooSoon' | 'result' | 'over';

class Game {
  private phases = new Phases<P>('ready');
  private wait = 0;
  private round = 0;
  private totalMs = 0;
  private lastMs = 0;
  private best = 0;
  private ctx: HostedGameContext | null = null;

  init(context: HostedGameContext): void {
    this.ctx = context;
    this.phases.reset('ready');
    this.round = 0;
    this.totalMs = 0;
    this.lastMs = 0;
  }

  private nextRound(): void {
    this.wait = rng.float(${minWait}, ${maxWait});
    this.phases.to('waiting');
  }

  update(dt: number, input: HostedInput): void {
    this.phases.advance(dt);
    const pressed = input.pressed(0, 'a') || input.pressed(0, 'start');

    if (this.phases.is('ready', 'over')) {
      if (pressed) { this.init(this.ctx!); this.nextRound(); }
      return;
    }
    if (this.phases.is('waiting')) {
      // Pressing early is its own outcome, not a silent no-op.
      if (pressed) { this.phases.to('tooSoon'); return; }
      if (this.phases.phaseFor >= this.wait) this.phases.to('now');
      return;
    }
    if (this.phases.is('now')) {
      if (pressed) {
        this.lastMs = Math.round(this.phases.phaseFor * 1000);
        this.totalMs += this.lastMs;
        this.round += 1;
        this.phases.to('result');
      }
      return;
    }
    if (this.phases.is('tooSoon')) {
      if (this.phases.after(1.0, 'waiting')) this.wait = rng.float(${minWait}, ${maxWait});
      return;
    }
    if (this.phases.is('result') && this.phases.phaseFor > 0.9) {
      if (this.round >= ${rounds}) {
        const average = Math.round(this.totalMs / Math.max(1, this.round));
        // Lower is better here, so "best" is a minimum — the one place the
        // toolbox's best-score shape does not fit, recorded rather than hidden.
        if (this.best === 0 || average < this.best) { this.best = average; this.ctx?.saveDirty(); }
        this.phases.to('over');
      } else {
        this.nextRound();
      }
    }
  }

  render(g: CanvasRenderingContext2D): void {
    clear(g, this.phases.is('now') ? 'lcdDeep' : 'bg');

    centered(g, 'ROUND ' + this.round + ' / ' + ${rounds}, 24, { size: 11, fill: 'muted' });
    if (this.best > 0) centered(g, 'BEST ' + this.best + 'MS', 40, { size: 11, fill: 'faint' });

    if (this.phases.is('ready')) centered(g, 'PRESS A TO START', H / 2, { size: 13 });
    if (this.phases.is('waiting')) centered(g, 'WAIT...', H / 2, { size: 13, fill: 'muted' });
    if (this.phases.is('now')) centered(g, 'PRESS', H / 2, { size: 20, fill: 'text' });
    if (this.phases.is('tooSoon')) centered(g, 'TOO SOON', H / 2, { size: 13, fill: 'danger' });
    if (this.phases.is('result')) centered(g, this.lastMs + ' MS', H / 2, { size: 16, fill: 'lcd' });
    if (this.phases.is('over')) {
      centered(g, 'AVERAGE ' + Math.round(this.totalMs / Math.max(1, this.round)) + ' MS', H / 2, { size: 14 });
      centered(g, 'PRESS A TO TRY AGAIN', H - 26, { size: 12, fill: 'muted' });
    }
  }
${saveMethods(spec)}}
${footer()}`;
}

function target(spec: GameSpec): string {
  const seconds = num(spec, 'seconds', 30);
  const targets = num(spec, 'targets', 1);

  return `${preamble(spec)}
type P = 'ready' | 'play' | 'over';

interface Mark { x: number; y: number; alive: boolean }

class Game {
  private phases = new Phases<P>('ready');
  private cursor = { x: W / 2, y: H / 2 };
  private marks: Mark[] = [];
  private score = 0;
  private best = 0;
  private ctx: HostedGameContext | null = null;

  init(context: HostedGameContext): void {
    this.ctx = context;
    this.phases.reset('ready');
    this.score = 0;
    this.cursor = { x: W / 2, y: H / 2 };
    this.place();
  }

  private place(): void {
    this.marks = Array.from({ length: ${targets} }, () => ({
      x: rng.float(28, W - 28), y: rng.float(56, H - 40), alive: true,
    }));
  }

  update(dt: number, input: HostedInput): void {
    this.phases.advance(dt);

    if (this.phases.is('ready', 'over')) {
      if (input.pressed(0, 'a') || input.pressed(0, 'start')) {
        if (this.phases.is('over')) this.init(this.ctx!);
        this.phases.to('play');
      }
      return;
    }

    const step = 150 * dt;
    if (input.held(0, 'left')) this.cursor.x -= step;
    if (input.held(0, 'right')) this.cursor.x += step;
    if (input.held(0, 'up')) this.cursor.y -= step;
    if (input.held(0, 'down')) this.cursor.y += step;
    this.cursor.x = Math.max(6, Math.min(W - 6, this.cursor.x));
    this.cursor.y = Math.max(6, Math.min(H - 6, this.cursor.y));

    if (input.pressed(0, 'a')) {
      for (const mark of this.marks) {
        if (!mark.alive) continue;
        if (Math.hypot(mark.x - this.cursor.x, mark.y - this.cursor.y) < 16) {
          mark.alive = false;
          this.score += 1;
          if (this.score > this.best) { this.best = this.score; this.ctx?.saveDirty(); }
        }
      }
      if (this.marks.every((mark) => !mark.alive)) this.place();
    }

    ${seconds > 0 ? `if (this.phases.phaseFor > ${seconds}) this.phases.to('over');` : ''}
  }

  render(g: CanvasRenderingContext2D): void {
    clear(g);
    for (const mark of this.marks) {
      if (mark.alive) { circle(g, mark.x, mark.y, 14, 'amber'); circle(g, mark.x, mark.y, 6, 'bg'); }
    }
    rect(g, this.cursor.x - 8, this.cursor.y - 1, 16, 2, 'lcd');
    rect(g, this.cursor.x - 1, this.cursor.y - 8, 2, 16, 'lcd');

    centered(g, 'HIT ' + String(this.score).padStart(2, '0'), 22, { size: 11, fill: 'muted' });
    centered(g, 'BEST ' + String(this.best).padStart(2, '0'), 38, { size: 11, fill: 'faint' });
    ${seconds > 0 ? `if (this.phases.is('play')) centered(g, String(Math.max(0, Math.ceil(${seconds} - this.phases.phaseFor))), 54, { size: 11, fill: 'faint' });` : ''}
    if (this.phases.is('ready')) centered(g, 'PRESS A TO START', H - 26, { size: 13 });
    if (this.phases.is('over')) centered(g, 'TIME — PRESS A', H - 26, { size: 13 });
  }
${saveMethods(spec)}}
${footer()}`;
}

const BUILDERS: Record<Kind, (spec: GameSpec) => string> = {
  collect,
  dodge,
  memory,
  reaction,
  target,
};

export function synthesize(spec: GameSpec): string {
  const build = BUILDERS[spec.kind as Kind];
  if (!build) throw new Error(`No way to build a "${spec.kind}" game.`);
  return build(spec);
}
